<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SelectOptionTree\Module'                        => __DIR__ . '/Module.php',
    'SelectOptionTree\Controller\SelectOptionTreeController' => __DIR__ . '/src/SelectOptionTree/Controller/SelectOptionTreeController.php',
    'SelectOptionTreeTest\Framework\TestCase'        => __DIR__ . '/tests/SelectOptionTree/Framework/TestCase.php',
    'SelectOptionTreeTest\SampleTest'                => __DIR__ . '/tests/SelectOptionTree/SampleTest.php',
);
