<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StickyNotes\Module'                        => __DIR__ . '/Module.php',
    'StickyNotes\Controller\StickyNotesController' => __DIR__ . '/src/StickyNotes/Controller/StickyNotesController.php',
    'StickyNotesTest\Framework\TestCase'        => __DIR__ . '/tests/StickyNotes/Framework/TestCase.php',
    'StickyNotesTest\SampleTest'                => __DIR__ . '/tests/StickyNotes/SampleTest.php',
);
