<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Taglist\Module'                        => __DIR__ . '/Module.php',
    'Taglist\Controller\TaglistController' => __DIR__ . '/src/Taglist/Controller/TaglistController.php',
    'TaglistTest\Framework\TestCase'        => __DIR__ . '/tests/Taglist/Framework/TestCase.php',
    'TaglistTest\SampleTest'                => __DIR__ . '/tests/Taglist/SampleTest.php',
);
