        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.optionTree.js')
                                      ->prependFile($this->basePath() . 'http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js') ?>

<BR/><BR/><BR/><BR/>
<strong>Module:</strong>        Taglist &raquo;
<strong>Controller:</strong>    Taglist &raquo;
<strong>Action:</strong>        index
<BR/><BR/>

<h1>Demo for TagList tree maintenance</h1>
When you have a tree with the layout 
id - name - parent

<table><tr><td>This taglist</td><td>modified by this</td><td>will give<td></td>
<tr><td>
$rows = array(
    'a' => array(
        'id' => 'a',
        'parent' => null
    ),
    'b' => array(
        'id' => 'b',
        'parent' => 'a'
    ),
    'c' => array(
        'id' => 'c',
        'parent' => 'a'
    ),
    'd' => array(
        'id' => 'd',
        'parent' => 'b'
    ),
    'e' => array(
        'id' => 'e',
        'parent' => 'b'
    ),
   'f' =>  array(
        'id' => 'f',
        'parent' => 'c'
    ),
);
</td><td>
$tree = array();
$toUnset = array();

//Traverse table
foreach($rows as $rowId => $r){
    if(!$r['parent']){
        continue;
    }
    $rows[$r['parent']]['childs'][$r['id']] = &$rows[$r['id']];
    $toUnset[] = $r['id'];
}

//Unset not root row
foreach($toUnset as $id){
    unset($rows[$id]);
}
</td><td>Array
(
    [a] => Array
        (
            [id] => a
            [parent] => 
            [childs] => Array
                (
                    [b] => Array
                        (
                            [id] => b
                            [parent] => a
                            [childs] => Array
                                (
                                    [d] => Array
                                        (
                                            [id] => d
                                            [parent] => b
                                        )

                                    [e] => Array
                                        (
                                            [id] => e
                                            [parent] => b
                                        )

                                )

                        )

                    [c] => Array
                        (
                            [id] => c
                            [parent] => a
                            [childs] => Array
                                (
                                    [f] => Array
                                        (
                                            [id] => f
                                            [parent] => c
                                        )

                                )

                        )

                )

        )

)
</td></tr></table>