<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Configure title'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('Configure subtitle') ?></p>
    <p><?php echo $this->translate('Configure paragraph') ?></p>

    <p><a class="btn btn-success btn-large" href="https://github.com/timvansteenbergen/fatboy" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 FatBoy on GitHub') ?> &raquo;</a></p>
</div>

