<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Fatboys title'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('Fatboys mission subtitle') ?></p>
    <p><?php echo $this->translate('Fatboys mission explainModules') ?></p>
    <p><?php echo $this->translate('Fatboys mission explainExtensions') ?></p>

    <p><a class="btn btn-success btn-large" href="https://github.com/timvansteenbergen/fatboy" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 FatBoy on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Use It title') ?></h2>
        <p><?php echo $this->translate('Use It paragraph') ?></p>
        <!--        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank">--><?php //echo $this->translate('ZF2 Development Portal') ?><!-- &raquo;</a></p>-->
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Evolve FatBoy title') ?></h2>
        <p><?php echo $this->translate('Evolve FatBoy paragraph') ?></p>
        <!--        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank">--><?php //echo $this->translate('Explore ZF2 Modules') ?><!-- &raquo;</a></p>-->
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Help and Support title') ?></h2>
        <p><?php echo $this->translate('Help and Support paragraph') ?></p>
        <!--       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank">--><?php //echo $this->translate('Ping us on IRC') ?><!-- &raquo;</a></p>-->
</div>
